### ISSUE TITLE
Bad Password bug

### ISSUE THREAD

**Issue by Talonflame193** [khcrysalis/Feather#196]
I found a weird bug, when you import your cert in feather it shows bad password when you need too long time, I solved this by reopening the app and import it faster.

**Comment by khcrysalis** [comment]
Explain better with a video

**Comment by Talonflame193** [comment]
I don't have a video but I could reproduce it many times. It says bad password when you open the app for the first time and try to import a cert. it only worked after restarting the app.

**Comment by khcrysalis** [comment]
Can you make a video

**Comment by Barborica-Alexandru** [comment]
I actually had this happen to me once also so there might be some validity to it. I have no logs or videos unfortunately since I thought it was just a problem with the cert that was hosted on my nextcloud and I had just replaced the file. But now seeing this issue I'm thinking it might not have been my fault.

**Comment by Talonflame193** [comment]
I can't send you videos because it always happened to people which I helped to get feather and I can't publish their screens. First I thought they just typed the pass wrong but since this happened like every time I think it might has to do something with feather. And as I said it's just like you import the 2 files and enter the password and it gives you a bad password

**Comment by castdrian** [comment]
I can reproduce this however,the debugger did not spit out anything useful, I'll investigate later when I get home

**Comment by djsmix** [comment]
> I can reproduce this however, the debugger did not spit out anything useful, I'll investigate later when I get home

Did you had a look?

**Comment by castdrian** [comment]
I did

**Comment by santhosh-D-subramani** [comment]
same happening for me , can’t add cert in feather , where esign adding it

**Comment by Talonflame193** [comment]
Seems to be fixed

**Comment by khcrysalis** [comment]
This should be fixed in the v2.0 rewrite (the issue was caused by not freeing the mobileprovision when checking the password afterwards, causing additional certificates after that one being allocated giving 'Bad Password'). Wait for next release, though I will reopen this if it hasn't been properly fixed.

**Comment by elmerfds** [comment]
FYI this still happens in v2.4.0 and it happens when you take too long to save the new certificate. 

Works if I add & save it quickly.

**Comment by claration** [comment]
> FYI this still happens in v2.4.0 and it happens when you take too long to save the new certificate. 
> 
> Works if I add & save it quickly.

The original fix was from not freeing properly, which I'm sure still works now. Though I do recommend making a new issue since this seems a bit different.

**Comment by jakeyounglol** [comment]
> FYI this still happens in v2.4.0 and it happens when you take too long to save the new certificate. 
> 
> Works if I add & save it quickly.

this is happening to me too, it's a very strange bug

**Comment by ricosuave0922** [comment]
> FYI this still happens in v2.4.0 and it happens when you take too long to save the new certificate.
> 
> Works if I add & save it quickly.

Same problem here on latest version. Adding and saving quickly does seem to work. It does cause feather to crash instantly after, but when relaunching the cert is there.
